docs/GettingStarted.md

Thought that it'd be nice if this was documented too.

Added explanation for 64-bit binaries

---

src/Core/Parser/ASTConverter.cs
src/Generator.Tests/AST/TestAST.cs
src/Generator/AST/VTables.cs

I created a solution file for monodevelop and when compiling encountered a few warnings and fixed them.

A few minor fixes.

---

src/AST/Declaration.cs
src/AST/Function.cs

Signed-off-by: Dimitar Dobrev <dpldobrev@yahoo.com>

Copied the signature and the line number when cloning functions

---

src/AST/Class.cs
src/Generator.Tests/Passes/TestPasses.cs
src/Generator/Generators/CSharp/CSharpTextTemplate.cs
src/Generator/Passes/CheckMacrosPass.cs
tests/Native/Passes.h

Did every change into one commit. The pull request is cleaner now! :)

Added CS_INTERNAL macro definition and test

---

src/Generator/Generators/CLI/CLISourcesTemplate.cs
src/Generator/Generators/CSharp/CSharpTextTemplate.cs
tests/Basic/Basic.h

Fixed all the changed in one commit and a mergeable PR...

Fixed code gen when using non primitive pointer type CS_OUT args.

---

src/Generator/Generators/CLI/CLIMarshal.cs
src/Generator/Generators/CLI/CLISourcesTemplate.cs
src/Generator/Generators/CSharp/CSharpTextTemplate.cs
tests/Basic/Basic.h

Added ParameterIndex to context when marshalling struct members. Also incorporated other changes.

Fixed code generation when using arrays in ValueType types.

---

src/Generator/Passes/ParamTypeToInterfacePass.cs
tests/CSharpTemp/CSharpTemp.Tests.cs
tests/CSharpTemp/CSharpTemp.cpp
tests/CSharpTemp/CSharpTemp.h

Had to put one extra check for Conversion and Explicit conversion operators...
I don't know if this is okay or we should change the the parameterKind for such operators!

Added param to interface pass for Operator functions.

---

src/Generator/Generators/CSharp/CSharpMarshal.cs
tests/CSharpTemp/CSharpTemp.Tests.cs

closes #514.
test added to tests/CSharpTemp/CSharpTemp.Tests.cs

closes #514.

---

src/Core/Parser/ASTConverter.cs
src/CppParser/AST.cpp
src/CppParser/AST.h
src/CppParser/Bindings/CLI/AST.cpp
src/CppParser/Bindings/CLI/AST.h
src/CppParser/Bindings/CLI/CppParser.cpp
src/CppParser/Bindings/CLI/CppParser.h
src/CppParser/Bindings/CLI/Target.cpp
src/CppParser/Bindings/CLI/Target.h
src/CppParser/Bindings/CSharp/i686-apple-darwin12.4.0/AST.cs
src/CppParser/Bindings/CSharp/i686-apple-darwin12.4.0/CppParser.cs
src/CppParser/Bindings/CSharp/i686-apple-darwin12.4.0/Target.cs
src/CppParser/Bindings/CSharp/i686-pc-win32-msvc/AST.cs
src/CppParser/Bindings/CSharp/i686-pc-win32-msvc/CppParser.cs
src/CppParser/Bindings/CSharp/i686-pc-win32-msvc/Target.cs
src/CppParser/Bindings/CSharp/x86_64-apple-darwin12.4.0/AST.cs
src/CppParser/Bindings/CSharp/x86_64-apple-darwin12.4.0/CppParser.cs
src/CppParser/Bindings/CSharp/x86_64-apple-darwin12.4.0/Target.cs
src/CppParser/Bindings/CSharp/x86_64-linux-gnu/AST.cs
src/CppParser/Bindings/CSharp/x86_64-linux-gnu/CppParser.cs
src/CppParser/Bindings/CSharp/x86_64-linux-gnu/Target.cs
src/Generator/Generators/CLI/CLIHeadersTemplate.cs
src/Generator/Generators/CLI/CLISourcesTemplate.cs
src/Generator/Generators/CSharp/CSharpTextTemplate.cs

Signed-off-by: Dimitar Dobrev <dpldobrev@yahoo.com>

Removed the memory leak in the AST converter

---

src/Generator/Generators/CSharp/CSharpMarshal.cs
src/Generator/Passes/CheckIgnoredDecls.cs
tests/CSharpTemp/CSharpTemp.Tests.cs
tests/CSharpTemp/CSharpTemp.h

Added marshalling of fixed size non primitive type arrays.

---

tests/CSharpTemp/CSharpTemp.Tests.cs

Replace "\r\n" with Environment.Newline

Fixed build on linux due to newline.

---

.gitignore
src/Generator/Generators/CSharp/CSharpTextTemplate.cs
tests/Basic/Basic.Tests.cs
tests/Basic/Basic.cpp
tests/Basic/Basic.h
tests/CSharpTemp/CSharpTemp.Tests.cs
tests/CSharpTemp/CSharpTemp.cpp
tests/CSharpTemp/CSharpTemp.cs
tests/CSharpTemp/CSharpTemp.h

@tritao @ddobrev Please review.

Fixed code gen for Out params (Value type and interfaces)

---

src/Generator/Generators/CSharp/CSharpMarshal.cs
tests/CSharp/CSharp.cpp
tests/CSharp/CSharp.h
tests/Tests.h

Fixed missing namespace problem.

---

src/Generator/Passes/CleanInvalidDeclNamesPass.cs
tests/Common/Common.Tests.cs
tests/Common/Common.h

Fix generation of functions with union params

---

src/AST/ASTVisitor.cs
src/AST/Declaration.cs
src/AST/Template.cs
src/Core/Parser/ASTConverter.cs
src/CppParser/AST.cpp
src/CppParser/AST.h
src/CppParser/Bindings/CLI/AST.cpp
src/CppParser/Bindings/CLI/AST.h
src/CppParser/Bindings/CSharp/i686-apple-darwin12.4.0/AST.cs
src/CppParser/Bindings/CSharp/i686-pc-win32-msvc/AST.cs
src/CppParser/Bindings/CSharp/x86_64-apple-darwin12.4.0/AST.cs
src/CppParser/Bindings/CSharp/x86_64-linux-gnu/AST.cs
src/CppParser/Bindings/CSharp/x86_64-pc-win32-msvc/AST.cs
src/CppParser/Parser.cpp
src/CppParser/Parser.h
src/Generator.Tests/AST/TestAST.cs
src/Generator/Generators/CLI/CLITypePrinter.cs
src/Generator/Generators/CSharp/CSharpTypePrinter.cs
src/Generator/Passes/CheckVirtualOverrideReturnCovariance.cs
src/Generator/Types/CppTypePrinter.cs
tests/Common/Common.cpp
tests/Common/Common.h

Partial fix for https://github.com/mono/CppSharp/issues/664.

Added support for C++11 type alias template declarations.

---

src/CLI/CLI.cs
src/CLI/Generator.cs
src/CLI/Options.cs
src/CLI/premake5.lua

Made the CLI options more standard and improved the help.

CLI improvements

---

src/CLI/CLI.cs
src/CLI/Generator.cs
src/CLI/Options.cs

Changed code to fit repository style and fixed wrong CLI application name (see #745)

Changed code to fit repository style and fixed wrong CLI application name

---

README.md

As requested by @ddobrev, add ChakraSharp to readme.

Add link to ChakraSharp in readme

---

README.md

I recently switched my bindings generator from ClangSharp to CppSharp.
As CppSharp is designed to support C++ I opted out the code generation part and used parser output only.
Despite it took a loot of effort - I managed to improve the quality of FFmpeg.AutoGen so much!
Thank you for your existence!

Add FFmpeg.AutoGen

---

src/Generator/Generators/CSharp/CSharpSources.cs
src/Generator/Options.cs

Let the marshal determine the size of the structure

---

src/AST/Class.cs
src/Generator/Generators/CSharp/CSharpSources.cs
src/Generator/Passes/CheckIgnoredDecls.cs
src/Generator/Passes/ResolveIncompleteDeclsPass.cs
src/Parser/ASTConverter.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.cpp
tests/CSharp/CSharp.h

They're stil W.I.P and template classes don't work yet.
This should fix #779

Incomplete classes and structs are now generated for C#.

---

src/Core/Toolchains/MSVCToolchain.cs

Fixing WinSDK include path code

---

src/Core/premake5.lua

Currently testing. Need to know whether CI passes here.

Use direct path to link to Microsoft.VisualStudio.Setup.Configuration.Interop

---

src/Generator/Driver.cs

Fixes https://github.com/mono/CppSharp/issues/802

Enabled users to remove any built-in pass.

---

src/CppParser/Bootstrap/Bootstrap.cs
src/Generator/Options.cs

Removed the Obsolete Options.Headers and Options.Libraries and replaced
it with module. Generator.cs and CLI.cs still need to be updated, though.
Fixes #766

Deleted Obsolete Options and replaced them with Modules

---

src/Generator/Generators/CSharp/CSharpMarshal.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.h

Fixed the generated C# when setting a field which is an array of complex objects

---

src/Generator/Generators/CSharp/CSharpSources.cs

Added check for native pointer for null before calling a destructor and set it to null afterwards

---

tests/VTables/VTables.Tests.cs

Included the TestVirtualFunctionRetVal for Linux

---

src/Generator/Generators/CSharp/CSharpMarshal.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.h

Fixed the generated C# for const ref parameter of Indexer

---

src/Generator/Types/TypeIgnoreChecker.cs
tests/CSharp/CSharp.h

Ignored the generated code for variable-sized array of a class/struct

---

src/Generator/Generators/CSharp/CSharpSources.cs
tests/Common/Common.Tests.cs
tests/Common/Common.cpp
tests/Common/Common.h

Fixed the generation of C# for Virtual function with std::string params

---

src/Generator.Tests/premake5.lua

Included the native AST.h to the solution

---

build/premake5.lua
src/Parser/ParserOptions.cs
src/Parser/premake5.lua

Added passage of VS Version selected at configuration time to the build

---

build/Tests.lua
src/Generator/Generators/CLI/CLITypeReferences.cs
tests/Common/Common.cs
tests/Common/premake4.lua

Fixed the generated #includes when renaming output files.

---

src/CppParser/Parser.cpp

Added clang headers' path to system includes

---

src/CppParser/Parser.cpp
src/Generator/Driver.cs
src/Parser/ParserOptions.cs

Added an option to enable or disable RTTI

---

src/Generator/BindingContext.cs
src/Generator/Generators/CSharp/CSharpTypePrinter.cs
src/Generator/Passes/DelegatesPass.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.cpp
tests/CSharp/CSharp.h

Fixed the C# generation for functions with typedefed function pointers as params

---

docs/BuildingLLVM.md
docs/GettingStarted.md

This unifies some of the steps and documents usage of some scripts that we added meanwhile to facilitate the process.

[docs] Update the getting started guide and LLVM compilation guide.

---

src/Parser/ParserOptions.cs

Just to complete the list @tritao :smile:

Add C++17 to the parser options

---

examples/Parser/Parser.cs
examples/Parser/premake5.lua

Signed-off-by: Joao Matos <joao@tritao.eu>

[examples] Added an example for the parser APIs.

---

src/Core/Toolchains/MSVCToolchain.cs

Fixed VS2017 system includes search error

---

src/Generator/Passes/CheckIgnoredDecls.cs
tests/CSharp/CSharpTemplates.h

Fixed incorrectly generated bindings for class with non-type template arguments

---

.gitignore

Also making line endings consistent within .gitignore

Adding vs2017 to .gitignore

---

src/Generator/Generators/CSharp/CSharpMarshal.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.h

fixes #1004 
I'm on Windows and there was docs only for testing on Linux and I have no experience with C# tests, so I was not able to actually run the test.

Fixed boolean arrays

---

.travis.yml
appveyor.yml
build/Compile.sh
build/Helpers.lua
src/CLI/Generator.cs
src/CppParser/ParserGen/ParserGen.cs
src/Generator.Tests/GeneratorTest.cs
src/Generator/Generators/CSharp/CSharpSources.cs
src/Generator/Generators/CodeGenerator.cs
src/Generator/Passes/CleanInvalidDeclNamesPass.cs
src/Generator/Passes/DelegatesPass.cs
src/Generator/Utils/BlockGenerator.cs
src/Generator/Utils/Utils.cs
src/Parser/ParserOptions.cs
tests/CSharp/CSharp.cs
tests/CSharp/CSharp.h

Please see commit messages for details on what was fixed. No point in repeating that here.
In addition to fixes i added `GenerateFormatted` option which forces producing formatted c# bindings code. This was not possible if wrapper was set to be compiled by CppSharp. In case this is unnecessary or unacceptable please let me know and i will nuke the commit.

Multiple fixes

---

build/scripts/LLVM.lua

Compiler kind (always gcc for now) and version (4.8/4.9/5/6/7) is now always included in llvm package name. Additionally if `--no-cxx11-abi` flag is passed to premake then package name will end wiht "-no-cxx11".
Prebuilt LLVM binaries package for CI needs renaming to `llvm-9bde5f-linux-x64-gcc-4.8-Release.tar.xz`.

Add compiler/abi information to LLVM package names on linux.

---

build/scripts/LLVM.lua

Fixes https://github.com/mono/CppSharp/issues/1032.

Update VS check when downloading pre-compiled LLVM packages.

---

src/Generator/Library.cs
src/Generator/Utils/ExpressionEvaluator.cs
src/Generator/premake5.lua
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.cs
tests/CSharp/CSharp.h

Fixes the main issues in #1047
ExpressionEvaluator was taken from https://github.com/codingseb/ExpressionEvaluator.

Evaluate expressions and set a default namespace for enums generated using GenerateEnumFromMacros

---

src/Core/Toolchains/XcodeToolchain.cs

Fixes #1061.
When merged, this PR will improve `XcodeToolchain.cs` to use `xcode-select` instead of inferring where the XCode SDK exists. If `xcode-select` fails for some reason, we default to the original behavior.

Implement xcode-select based path selection

---

src/Generator/Types/Std/Stdlib.cs
tests/Common/Common.Tests.cs
tests/Common/Common.cpp
tests/Common/Common.h

Fix for issue https://github.com/mono/CppSharp/issues/1096

Added parameter index to managed marshal variables

---

src/Core/Toolchains/MSVCToolchain.cs

Make Windows10SDK detection more robust

---

src/Generator/Generators/CLI/CLIMarshal.cs
tests/Common/Common.Tests.cs
tests/Common/Common.cpp
tests/Common/Common.h

Non primitive arrays are not being marshalled correctly for C++/CLI.

Marshal non primitive fixed arrays.

---

src/Generator/Generators/CSharp/CSharpSources.cs

Virtual tables are the same object per class in C++.

Made the original virtual tables static too

---

src/Generator/AST/VTables.cs
src/Generator/Generators/CSharp/CSharpSources.cs
tests/VTables/VTables.Tests.cs
tests/VTables/VTables.cpp
tests/VTables/VTables.cs
tests/VTables/VTables.h
tests/VTables/premake4.lua

Fixes https://github.com/mono/CppSharp/issues/1151.

Fix patching of virtual tables for MSVC with RTTI

---

src/Generator/Passes/CleanInvalidDeclNamesPass.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.h
tests/CSharp/ExcludedUnit.hpp

Fix anonymous member name colliding with enclosing type name

---

src/Generator/Passes/CheckAbiParameters.cs

Fix wrong generated destructor

---

src/Generator/Generators/CSharp/CSharpSources.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.cpp
tests/CSharp/CSharp.h

Fix wrong marshalling for static member arrays

---

src/Generator/Types/Std/Stdlib.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.cpp
tests/CSharp/CSharp.h

Fix wrong [MarshalAs(UnmanagedType)] for strings

---

src/Generator/Passes/CheckAbiParameters.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.cpp
tests/CSharp/CSharp.h
tests/Tests.h

Fix PInvokeStackImbalance when calling C++ methods

---

src/Generator/Passes/CheckAmbiguousFunctions.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.cpp
tests/CSharp/CSharp.h

Fix ambiguous conversion functions

---

build/Tests.lua

Visual Studio - Test Explorer requires it.

Use NUnit3TestAdapter package

---

tests/CSharp/CSharp.Tests.cs

See https://github.com/mono/CppSharp/issues/1518.

Ignore test because something that has not been implemented cant be tested

---

.github/workflows/main.yml

publish cppsharp artifacts along with required dependencies

publish artifacts

---

build/intrin.ps1

See https://github.com/mono/CppSharp/issues/1556

Fix intrin.ps1

---

include/CppSharp.h

Generate XML Documentation Files

document syntax warning

---

src/Generator/Passes/FieldToPropertyPass.cs

CppSharp forget to generate comment for filed
before(C#):
after(C#):
before(CLI):
after(CLI):

generate comment for field

---

.gitignore
nuget.config
src/Generator/Extensions/LayoutFieldExtensions.cs
src/Generator/Generators/CSharp/CSharpMarshal.cs
src/Generator/Generators/CSharp/CSharpSources.cs
src/Generator/Generators/CodeGenerator.cs
tests/CSharp/CSharp.Tests.cs
tests/CSharp/CSharp.cpp
tests/CSharp/CSharp.h

See issue #1598 for description.

Embedded array of struct issues. Resolves mono/CppSharp#1598

---

src/Generator/Extensions/PrimitiveTypeExtensions.cs

Fix NotImplementedException for signed char
