mono/CppSharp

src/CppParser/Parser.cpp
The build fails on osx 10.10 building CppSharp for 64 bits using the recommended llvm version with the following error:
```
==== Building CppSharp.CppParser (release_x64) ====
AST.cpp
Comments.cpp
CppParser.cpp
Parser.cpp
../../../src/CppParser/Parser.cpp:2415:58: error: unexpected ':' in nested name specifier; did you mean '::'?
auto USR = GetDeclUSR(FriendDecl ? (Decl*)FriendDecl : FD);
^
::
../../../src/CppParser/Parser.cpp:2415:47: error: no member named 'FD' in 'clang::FriendDecl'; did you mean simply 'FD'?
auto USR = GetDeclUSR(FriendDecl ? (Decl*)FriendDecl : FD);
^~~~~~~~~~~~~~~
FD
../../../src/CppParser/Parser.cpp:2404:47: note: 'FD' declared here
Friend* Parser::WalkFriend(clang::FriendDecl *FD)
^
../../../src/CppParser/Parser.cpp:2415:62: error: expected ':'
auto USR = …
```
=> Fix build error on osx

src/CppParser/Bindings/premake4.lua
This reads the bitness from mono which is in path.
lipo -info gives the following output on a 64 bit mono:
```
localhost:build Stephan$ lipo -info `which mono`
Non-fat file: /usr/local/bin/mono is architecture: x86_64
```
With the executable from the Mono MDK the following is returned:
```
localhost:build Stephan$ lipo -info /Library/Frameworks/Mono.framework/Mono
Non-fat file: /Library/Frameworks/Mono.framework/Mono is architecture: i386
```
This patch checks for x86_64 in the output if found a 64 bit build is configured, else 32 bit.
=> Determine bitness on osx

src/Generator.Tests/GeneratorTest.cs
On osx clang's libc++ must be used for C++11 support. This patch checks whether we're on osx and adds the option ``` -stdlib=libc++ ``` Fixes #423
=> Use libc++ on osx

src/Generator.Tests/GeneratorTest.cs
For some reason premake didn't rebuild when I changed this and no compile error was thrown.
=> Add missing reference

src/Generator/Passes/Pass.cs
CppSharp master fails compiling QtSharp in https://github.com/mono/CppSharp/blob/master/src/Generator/Passes/RenameRootNamespaces.cs#L18 because one of the filenames is invalid and an ArgumentException is thrown when accessing the FileName.
Returning false on invalid units will stop the RenameNamespacePass before accessing the FileName property.
=> Don't visit invalid units

build/Tests.lua, src/AST/Declaration.cs, src/Generator/AST/ASTRecord.cs, src/Generator/Driver.cs, src/Generator/Generators/CLI/CLIMarshal.cs, src/Generator/Generators/CLI/CLITypeReferences.cs, src/Generator/Passes/GenerateAnonymousDelegatesPass.cs, tests/Basic/AnotherUnit.cpp, tests/Basic/AnotherUnit.h, tests/Basic/Basic.Tests.cs, tests/Basic/Basic.cpp, tests/Basic/Basic.cs, tests/Basic/Basic.h, tests/Basic/premake4.lua
Function pointers are converted to delegates which are marshalled using GetDelegateForFunctionPointer and GetFunctionPointerForDelegate. If the function pointers are typedef'd this works fine because a delegate is generated for each typedef. If it's just a plain function pointer then Action<> or Func<> is used, which fails because the marshalling functions can't deal with generic types. I've added a new pass which generates delegates for these function pointers to work around this issue.
I'm obviously not particularly familiar with the code base, so any thoughts on how this might be done better are welcome.
=> Generate delegates for non-typedef'd function pointers to prevent runtime exceptions during marshalling

src/CppParser/Parser.cpp, src/Generator.Tests/AST/TestAST.cs, tests/Native/AST.h
This reverts commit 7d5e53e1df611e8dad5f3106c5d7775d6c841260.
Conflicts:
tests/Native/AST.h
Signed-off-by: Dimitar Dobrev <dpldobrev@yahoo.com>
=> Revert "Fixed parsing of function signatures with const-qualified return types"

src/Generator/Generators/CSharp/CSharpTextTemplate.cs, src/Generator/Passes/CleanInvalidDeclNamesPass.cs, tests/Basic/Basic.h
The [double underscore] identifier was generated for anonymous types and hence resulted in conflict when nesting more than one anonymous types.
I checked if an identifier had just '_' in it then i repeated the underscore 'numSafeIden' times which kept track of how many times such identifier has been generated.
.
Alternate solution (probably more elegant) can be if [double underscore] was to be suffixed with integer 'numSafeIden' instead of repeating the underscore so many times.
=> Fixed compilation issues when nesting more than one anonymous types.

src/AST/TranslationUnit.cs, src/Generator/Passes/CheckIgnoredDecls.cs, src/Generator/Types/Types.cs
A few properties actually had really slow bodies. On the other hand, as properties they were used without saving their values in local variables. So I changed those to methods in order to let users know they should cache the results instead of making multiple calls.
=> Optimised the passes for time

src/Generator/Generators/CSharp/CSharpTextTemplate.cs, tests/CSharpTemp/CSharpTemp.h
Just a query. Is it intended to not generate setter for a static variable? If so, why?
Also, how do I write test for it without a setter?
=> Fixed getter code for static Ref Type arrays.

src/Generator/Generators/CSharp/CSharpTextTemplate.cs, tests/CSharp/CSharp.cpp, tests/CSharp/CSharp.h
This is my initial thought as I found that ```desugered``` is always the class required. I couldn't find a way to figure out if the parameter type is interface. So, probably it will change as currently it generates the cast for every argument whether required or not.
=> Fix for fn call when def argument is interface.

src/Runtime/SymbolResolver.cs
This change allows ResolveSymbol to find a library by
1. the current directory or a specified directory
2. the directories within the system path
QtSharp uses ResolveSymbol when getting the QMetaObject of a class, however without this change it's unable to find the Qt dll's unless they're in the current directory. With this change as long as the Qt libs are in the system path ResolveSymbol is able to find them.
=> Added the ability to search the machine Path for ResolveSymbol

build/LLVM.lua, src/CppParser/Parser.cpp
Basic changes to compile under VS2015 (Update 3) and link with Clang 3.8.1
=> Changes for VS2015 and Clang 3.8.1

docs/BuildingLLVM.md
I updated the BuildingLLVM.md so people trying to build CppSharp against a more recent Mono won't run into the issue where LLVM needs to be packaged in a certain way for the CppSharp build to work. Windows and Linux build instructions should probably be updated accordingly, but I can't test how their build scripts work.
=> Document LLVM build using premake on OSX

src/Generator/Generators/CLI/CLIMarshal.cs, src/Generator/Generators/CLI/CLITypePrinter.cs, src/Generator/Generators/CSharp/CSharpMarshal.cs, src/Generator/Generators/CSharp/CSharpTypePrinter.cs
@ddobrev please review and see if it makes sense to change all these instances to qualified visitation.
The tests seem to pass but I am not sure about making these changes.
=> Use the qualified pointee type when printing/visiting pointer types.

build/scripts/LLVM.lua
See issue #718.
DownloadDeps.bat looked for a string in the form like "Version
<number>.<number>.<number>.<number> for <arch>" but this doesn't work
for installations of Visual Studio that are not English.
Changed the regex to make it user language agnostic.
=> Fixed DownloadDeps.bat with Visual Studio

src/Generator/Generators/CLI/CLITemplate.cs
Before, when generating CLI code, the comment text is not commented out. e.g.
Original.h
~~~
/**
* This adds foo.
*
* @param foo  the first argument
* @return  the result
*/
int FooAdd(int foo);
~~~
Generated.h
~~~
/// <summary>
This adds foo.
/// </summary>
static int FooAdd(int foo);
~~~
Now, the generated code will comment out the comment text. e.g.
Generated.h
~~~
/// <summary>
/// This adds foo.
/// </summary>
static int FooAdd(int foo);
~~~
=> Made sure CLI comment block text is commented out.

build/GenerateProjects.bat, build/Helpers.lua, build/scripts/LLVM.lua
Fixed also the regex for finding ms build tools.
It's required to open the batch files with the developer command prompt
of vs 2017 !
Currently the premake version is still _not_ up to date! It's comming next!
=> Added support for VS 2017 project generation

src/Generator/Generators/CLI/CLIMarshal.cs, src/Generator/Generators/CSharp/CSharpMarshal.cs, tests/Common/Common.Tests.cs, tests/Common/Common.cpp, tests/Common/Common.h
Which were due to nullptr arguments in Marshaling native.
=> Fixed ArgumentException 

src/Generator/Passes/CheckStaticClass.cs, tests/Common/Common.Tests.cs, tests/Common/Common.cpp, tests/Common/Common.h
Fixes #743  
I had to change protected members to private as in C# static class cannot have protected members...  
Also, the way to check static is taken from [here](http://stackoverflow.com/questions/1175888/determine-if-a-type-is-static).  
Although my NUnit 2.0 could not find any tests, so I I haven't run the test after edit, but most probably it should pass. Do I need NUnit 3.0 to run the tests?
=> Fix CheckStaticClass pass and add test.

src/CppParser/Parser.cpp, src/Generator/Passes/RenamePass.cs
This is a bugfix for critical bug. With the fix the generation of the parser bindings should be nearly correct.
=> Fixed wrong recording of declaration order

README.md, src/CppParser/AST.cpp, src/CppParser/AST.h, src/CppParser/Bindings/CLI/AST.cpp, src/CppParser/Bindings/CLI/AST.h, src/CppParser/Bindings/CLI/CppParser.cpp, src/CppParser/Bindings/CLI/CppParser.h, src/CppParser/Bindings/CLI/Target.cpp, src/CppParser/Bindings/CLI/Target.h, src/CppParser/Bindings/CSharp/i686-apple-darwin12.4.0/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/i686-apple-darwin12.4.0/Std.cs, src/CppParser/Bindings/CSharp/i686-pc-win32-msvc/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/i686-pc-win32-msvc/Std.cs, src/CppParser/Bindings/CSharp/x86_64-apple-darwin12.4.0/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/x86_64-apple-darwin12.4.0/Std.cs, src/CppParser/Bindings/CSharp/x86_64-linux-gnu-cxx11abi/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/x86_64-linux-gnu-cxx11abi/Std.cs, src/CppParser/Bindings/CSharp/x86_64-linux-gnu/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/x86_64-linux-gnu/Std.cs, src/CppParser/Bindings/CSharp/x86_64-pc-win32-msvc/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/x86_64-pc-win32-msvc/Std.cs, src/CppParser/Comments.cpp, src/CppParser/CppParser.cpp, src/CppParser/CppParser.h, src/CppParser/Helpers.h, src/CppParser/Parser.cpp, src/CppParser/ParserGen/ParserGen.cs, src/CppParser/Target.h
=> Removed the macro in C++ AST for std::string because we can marshal it

build/LLVM.lua
Prevented projects from being generated using GenerateProjects.bat
=> Fix the typo in LLVM.lua

src/Core/Toolchains/ManagedToolchain.cs
=> Linux toolchain can be supplied in the same spirit in path probing on Mac.

src/CLI/CLI.cs, src/CLI/Generator.cs, src/CppParser/Bootstrap/Bootstrap.cs, src/CppParser/ParserGen/ParserGen.cs, src/Parser/ASTConverter.cs
* Fixed two warnings due to unused variables.
* Added more system include dirs. Covers at least Archlinux, maybe some other distros as well.
* Fixed build errors in `Bootstrap.cs`.
* Removed parsing of `CppSharp.CppParser.lib` of as per @ddobrev's instructions.
=> Linux fixes, Bootstrap.cs build errors, warnings

build/Helpers.lua
In some environments mono defaults building managed targets in architecture different from the host (like AnyCPU or x86 on x64 host). For example on x64 host (linux) build system would produce i686 architecture managed executables while native libraries are built as amd64. In such case managed executables are unable to load native libraries because they target different native architectures. This change ensures architecture consistency between all built binaries.
=> Force-set platform type to managed targets.

.gitignore, build/scripts/LLVM.lua
Exact requires commits are downloaded. Entire process is now limited by your internet connection speed + archive unpacking.
One thing to watch out - at least on linux `os.rmdir` fails to remove some symlinks. Must be premake limitation. I have to manually delete that directory.
Edit:
`package_llvm` command creates archive with wrong commit hash. Do not merge until fixed.
=> Cloning llvm from git replaced with downloading archives 

build/scripts/LLVM.lua
These libs are not used by current official CppSharp binary distributions of LLVM, however building LLVM locally will pick these libs up and link to them if they are installed on local system. Since premake does not link to any of those libs linking to local LLVM build will cause `DllNotFoundException` due to missing symbols.
=> Explicitly disable use of libedit, zlib, terminfo and libxml2 in LLVM builds

build/LLVM.lua
`get_llvm_build_dir()` returns directory `<llvm_dir>/build`. It is incorrect when using non-packaged LLVM build, because LLVM is built into `'deps/llvm/'..get_llvm_package_name()`. This change fixes issue where using unpackaged LLVM build resulted in `error: ‘StrictFP’ is not a member of ‘llvm::Attribute’`.
=> Use correct LLVM build dir for includes from unpackaged LLVM builds

build/Helpers.lua, build/scripts/LLVM.lua, src/CppParser/Bindings/CSharp/premake5.lua, src/CppParser/premake5.lua
GCC version is checked, if version is 4.8 or lower then cxx11 ABI is disabled. Added new `--no-cxx11-abi` option. It explicitly disables cxx11 ABI even on new compilers. This option is also taken into account when building LLVM.
=> Enable cxx11 abi for GCC 4.9+ on linux.

build/LLVM.lua, build/scripts/LLVM.lua
This change prevents premake from inserting /usr/lib64 search path on linux. GCC does not need this path specified compiler automatically knows where to look for system libs. Insertion of this path causes issues system has clang/llvm libs installed. Build would link to system libraries instead of custom required by CppSharp.
Also this patch revealed that linking to `pthread`, `z` and `tinfo` libraries on linux is not necessary and disabling them in LLVM build config works. Linking to these libs was removed. As you probably have guessed in the past CppSharp would throw `DllNotFoundException` due to missing symbols because it linked to system LLVM libs, not custom in-tree LLVM build.
This should be a final piece of the puzzle to linux builds. Binaries produced by `build/Compile.sh` can now …
=> Fix linking to LLVM libs on linux, when system has llvm/clang installed.

src/AST/Module.cs, src/Generator/Driver.cs
I came to need of this when converting native `Color` type to `System.Drawing.Color`. .net type requires reference to extra assembly. This will probably be useful for more types as well.
=> Add ability for managed module wrapper to reference extra assemblies.

src/AST/Method.cs, src/Generator/Library.cs, src/Generator/Options.cs, src/Generator/Passes/GetterSetterToPropertyPass.cs, src/Generator/Passes/verbs.txt
Remove internal class from `GetterSetterToPropertyPass` and make some methods `protected virtual` in order to allow customization of this pass.
`GetterSetterToPropertyPass` is trying to be too smart and converts too many things to properties. One such example is `void Run()` method getting converted to property, which makes no sense. I can not tell original intention behind logic in `IsGetter()` so instead of changing it i propose moving everything from private `PropertyGenerator` class to `GetterSetterToPropertyPass` and making some methods virtual so user may inherit this class, override some methods and replace the pass.
My personal opinion is that CppSharp is trying to be too smart here. Converting obvious things to properties (methods stating with "get"/"set" and maybe "is") is fine, …
=> GetterSetterToPropertyPass customization

src/Generator/Generators/CSharp/CSharpSources.cs, src/Generator/Generators/CSharp/CSharpSourcesExtensions.cs, tests/Common/Common.Tests.cs, tests/Common/Common.cpp, tests/Common/Common.h
My attempt at least. I am unsure this is entirely correct. Especially `if (!field.Type.IsPrimitiveType() && !(field.Type is TagType))` check. Please verify.
P.S. also slipped in fix in `CSharpSourcesExtensions.cs` where invalid code was generated. Error complained about compiler being unable to deduce type.
=> Fix for #1043

src/Generator/Passes/GenerateSymbolsPass.cs, src/Parser/ParserOptions.cs
As title says.
Also slipped in benign change adding extra include path for linux. Fixes error when including `limits.h`.
=> Fix for #1051

src/CLI/CLI.cs, src/Core/Diagnostics.cs
Fixes #1077 
Also renamed `messages` to `errorMessages` because that's what they are, and they are going to stderr.
=> Write error messages to stderr, renamed `messages` to `errorMessages`

src/AST/CppTypePrinter.cs, src/Generator/Generators/CSharp/CSharpMarshal.cs, src/Generator/Generators/CSharp/CSharpSources.cs, src/Generator/Generators/CSharp/CSharpTypePrinter.cs, src/Generator/Types/Std/Stdlib.cs, src/Generator/Types/TypeMapDatabase.cs, tests/CSharp/CSharp.cpp, tests/CSharp/CSharp.cs, tests/CSharp/CSharp.h
const char*, const char16_t* and const wchar_t* in particular.
This enables comparison of types when resolving ambiguity.
=> Added type maps for primitive strings (pointers to char)

src/CLI/Generator.cs
The problem being fixed is that although --rtti is given as argument to
CppSharp.CLI.exe the runtime type information is turned off. The error
is happening because the Generator options are copied over to the
parserOptions after the parserOptions have been used to generate the
cmake call. Thus, the default value of RTTI (off) is always evaluated
and cmake will always get the parameter -fno-rtti.
The same issue seems to apply to the unity build.
This patch fixes the issue by moving the 2 assignments of Generator
options properties into ParserOptions properties before they are
evaluated in parserOptions.Setup();
=> fixes #1191 CppSharp.CLI.exe --rtti sets -fno-rtti to clang

src/Generator/Generators/CSharp/CSharpTypePrinter.cs, src/Generator/Passes/DelegatesPass.cs, tests/CSharp/CSharp.Tests.cs, tests/CSharp/CSharp.h
```
struct fieldspointers
{
int(*funcint)(int(*bug)());
};
```
[Result](https://gist.github.com/AleXr64/65b04836e000f4798db48df2cba88faf)
BTW, review requested
=> Fix generating delegates for cases like https://github.com/mono/CppSharp/issues/1144

src/AST/FunctionExtensions.cs, src/CppParser/Parser.cpp, src/Generator/Driver.cs, src/Generator/Generators/CSharp/CSharpGenerator.cs, src/Generator/Passes/HandleDefaultParamValuesPass.cs, tests/CSharp/CSharp.Tests.cs, tests/CSharp/CSharp.cpp, tests/CSharp/CSharp.h
This bug is revealed by properly fixing the reading of ABI parameters in the parser.
=> Fix default arguments to only map to null if pointers

src/Generator/Driver.cs, src/Generator/Generators/CSharp/CSharpSources.cs, src/Generator/Passes/FlattenAnonymousTypesToFields.cs, tests/Common/Common.Tests.cs, tests/Common/Common.cpp, tests/Common/Common.h
This improves our generated API as we no longer need "_0"-like names and also prevents conflicts between an anonymous type and a property of this type.
=> Flatten anonymous types to avoid empty names

src/Generator.Tests/Passes/TestPasses.cs, src/Generator/Library.cs, tests/Native/Passes.h
I am not sure how to add a unit tests, there does not seems to be a tests file for Library.cs, so I could not update the tests.
I ran the existing tests and they passed.
Fixes #1264
=> Fix enum with zeros for hex literals

src/Generator/Passes/CheckVirtualOverrideReturnCovariance.cs, tests/Common/Common.h
Fixes https://github.com/mono/CppSharp/issues/1266.
=> Fix template type checking in CovariantTypeComparer.

src/AST/ASTVisitor.cs, src/AST/Declaration.cs, src/AST/Template.cs, src/AST/Type.cs, src/CppParser/AST.cpp, src/CppParser/Bindings/CLI/Decl.cpp, src/CppParser/Bindings/CLI/Decl.h, src/CppParser/Bindings/CLI/Types.cpp, src/CppParser/Bindings/CLI/Types.h, src/CppParser/Bindings/CSharp/i686-apple-darwin12.4.0/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/i686-pc-win32-msvc/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/x86_64-apple-darwin12.4.0/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/x86_64-linux-gnu-cxx11abi/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/x86_64-linux-gnu/CppSharp.CppParser.cs, src/CppParser/Bindings/CSharp/x86_64-pc-win32-msvc/CppSharp.CppParser.cs, src/CppParser/Decl.h, src/CppParser/Parser.cpp, src/CppParser/Parser.h, src/CppParser/Types.h, src/Generator.Tests/AST/TestAST.cs, src/Generator/Generators/CodeGenerator.cs, src/Generator/Generators/TypePrinter.cs, src/Parser/ASTConverter.cs, tests/Common/Common.h
Fixes https://github.com/mono/CppSharp/issues/1235.
WIP: Still missing generated parser bindings for non-Mac platforms.
=> Implement UnresolvedUsingType and UnresolvedUsingTypename.

src/CppParser/Parser.cpp, src/Generator.Tests/ReadNativeSymbolsTest.cs
See https://bugs.llvm.org/show_bug.cgi?id=44433.
=> Work around MSVC 32 crashing reading of exported symbols in Mach-O

src/Generator/Generators/CSharp/CSharpSources.cs, src/Generator/Passes/MultipleInheritancePass.cs, tests/CSharp/CSharp.Tests.cs, tests/CSharp/CSharp.h
The test has also uncovered a bug where the call to a primary base isn't always adjusted so the fix is extended accordingly.
=> Fix a crash for secondary bases with secondary bases

src/Generator/Types/Std/Stdlib.cs, tests/StandardLib/StandardLib.h
We have situations where we are using a `std::vector` typedef. Make sure `Desugar` is called on the type before it is marshalled, so that we get the underlying vector type of the typedef.
=> Ensure typedefs of std::vector are mapped

include/CppSharp.h
CppSharp.h uses the cli array type, however it does not prefix it with the cli namespace. This causes conflicts with std array, or other types called array.
=> add cli namespace to header to ensure the array type does not conflicts

src/Generator/Generators/CLI/CLIHeaders.cs, src/Generator/Generators/CLI/CLIMarshal.cs, src/Generator/Generators/CLI/CLISources.cs, src/Generator/Utils/BlockGenerator.cs
Add body blocks for ctor, dtor and finalizer to allow consumer to modify these methods bodies.
Create a ctor overload that takes a bool from the caller to tell the wrapper if it should own the native pointer passed to it, therefore making it responsible for deleting it later, or the caller is the only owner of the pointer.
Didn't think there were any tests needed as it is only generating a new ctor, which can be verified by looking at the generated code. How the ctor is used is up to the consumer.
=> Ctor, dtor and finalizer body blocks

src/Generator/Generators/CLI/CLIMarshal.cs, src/Generator/Generators/CLI/CLITypePrinter.cs, tests/CLI/CLI.Tests.cs, tests/CLI/CLI.cpp, tests/CLI/CLI.cs, tests/CLI/CLI.h
- Enum passed by reference is getting treated as a raw pointer, where enum is being dereferenced when it shouldn't.
- Full qualified enum name is not being used when generating enum param.
=> By reference enum param fixes

src/Generator/AST/ASTRecord.cs, src/Generator/Generators/CLI/CLITypeReferences.cs, tests/CLI/CLI.Tests.cs, tests/CLI/CLI.h, tests/CLI/NestedEnumInClassTest/ClassWithNestedEnum.cpp, tests/CLI/NestedEnumInClassTest/ClassWithNestedEnum.h, tests/CLI/NestedEnumInClassTest/NestedEnumConsumer.cpp, tests/CLI/NestedEnumInClassTest/NestedEnumConsumer.h, tests/CLI/premake4.lua
This fixes an issues where if a consumer is using an enum that is nested in another class, the generated header for the consumer cannot see the enum because the header where the enum lives is not included.
P.S - I think this might be the last fix I need to get things working on my side. I'll see what happens, so there may be other possible future PRs.
When does the master branch normally get published to NuGet?
Thanks.
=> Include type ref header in consumer header if type is nested enum

src/Generator/Generators/C/CppTypePrinter.cs, tests/CLI/CLI.Tests.cs, tests/CLI/CLI.cpp, tests/CLI/CLI.cs, tests/CLI/CLI.h
`CppTypePrinter.VisitTagType` has changed recently to use type maps, which consequently calls `CppSignatureType` instead of the previous `tag.Declaration.Visit(this)` call. This is breaking code generation for us as we are using `CustomType` for some tag types mapping.
The fix is to return the `UnsupportedType` (`CustomType` base) description instead of an empty string so that we can generate the correct type name, instead of `void*`, which is what is currently getting generated.
@tritao @ddobrev If you're happy with this PR, it would be really appreciated if we can get another NuGet release please. Unfortunately I just found this issue when testing the latest NuGet release.
Thank you.
=> Use UnsupportedType description for type name instead of empty string

appveyor.yml
The clang lib folder is not published on windows appveyor build. The lib folder is required to run the generator. This is useful if we want to test a build of CppSharp when a NuGet package is not available.
=> publish the clang lib folder

build/premake5-linux
building on some docker container /bin/sh default is dash, so that follow warning occurs
```
./premake5-linux: 3: ./premake5-linux: Bad substitution
```
this PR changes /bin/sh to /bin/bash in order to avoid error on `${BASH_SOURCE[0]}` expansion
=> force bash use in ./premake5-linux

src/CppParser/Parser.cpp, tests/CSharp/CSharp.h
=> Fix crash when trying to read a CXXRecordDecl that doesn't have a definition

src/CppParser/Parser.cpp
=> Ignore non-const data() method for std types like basic_string [c++17]

src/Generator/Passes/SymbolsCodeGenerator.cs
=> Fix generated constructor cant use `placement new` when class overloads `operator new`

src/AST/ASTVisitor.cs, tests/CSharp/CSharp.h
=> Add missing `Variable.Type` null check.

build/Helpers.lua, src/Generator/Passes/HandleDefaultParamValuesPass.cs, tests/CSharp/CSharp.cpp, tests/CSharp/CSharp.h
Fixes #1410 but not completely since using a nested expression that uses a class with leading underscore will still break but those 2 cases combined should be extremely rare. I'm not using C#'s `default literal` in nested expressions because there is potential for ambiguity.
According to the source code comment the order of `HandleDefaultParamValuePass` can't be changed. If there is a better way let me know but regardless it can always be implemented at a later time.
=> Use C# 'default literal' to avoid using a type's name that may be renamed

src/CppParser/Parser.cpp, tests/CSharp/CSharp.cpp, tests/CSharp/CSharp.h
There is no reason why it also shouldn't work for the 'u8' character literal but it requires C++17 and
* Changing the `LanguageVersion` to C++17 for the test projects breaks 2 tests (`defaultNonEmptyCtor` and `defaultNonEmptyCtorWithNullPtr`)
* I wasn't sure if I was allowed to change it anyways
=> Add support for C++ character literals (u, U, L)

appveyor.yml
Travis-CI doesn't have the limitation to only build from master.
=> Allow AppVeyor to trigger builds on any branch

src/Generator/Types/Std/Stdlib.cs, src/Runtime/MarshalUtil.cs
// DEBUG: DLL_API const wchar_t* TestCSharpStringWide(const wchar_t* in, CS_OUT const wchar_t** out)
Before
```.cs
public static string TestCSharpStringWide(string @in, out string @out)
{
var __arg1 = global::System.IntPtr.Zero;
var __ret = __Internal.TestCSharpStringWide(@in, &__arg1);
if (__arg1 == global::System.IntPtr.Zero)
{
@out = default(string);
return default; // Bug: completely ignoring __ret
}
var __retPtr1 = (short*) __arg1;
int __length1 = 0;
while (*(__retPtr1++) != 0) __length1 += sizeof(short);
@out = global::System.Text.Encoding.Unicode.GetString((byte*) __arg1, __length1);
if (__ret == global::System.IntPtr.Zero)
return default(string);
var __retPtr0 = (short*) __ret;
int __length0 = 0;
while (*(__retPtr0++) != 0) __length0 += sizeof(short);
return …
```
=> Fix string marshalling bug and move hard to read code to CppSharp.Runtime

build/Helpers.lua, src/Generator/Generators/CSharp/CSharpMarshal.cs, src/Runtime/MarshalUtil.cs, tests/CSharp/CSharp.Tests.cs, tests/CSharp/CSharp.cpp, tests/CSharp/CSharp.h
Before & After:
```.cs
public static global::System.IntPtr[] VoidPtrArray
{
get
{
var __ptr = (global::System.IntPtr*)CppSharp.SymbolResolver.ResolveSymbol("CSharp.Native.dll", "?VoidPtrArray@StaticVariables@@2PAPEBXA");
global::System.IntPtr[] __value = null;
if (__ptr != null)
{
__value = new global::System.IntPtr[2];
for (int i = 0; i < 2; i++)
__value[i] = new global::System.IntPtr(__ptr[i]); // Bug: cannot convert from System.IntPtr to int
}
return __value;
}
}
public static global::System.IntPtr[] VoidPtrArray
{
get
{
var __ptr = (global::System.IntPtr*)CppSharp.SymbolResolver.ResolveSymbol("CSharp.Native.dll", "?VoidPtrArray@StaticVariables@@2PAPEBXA");
return CppSharp.Runtime.MarshalUtil.GetIntPtrArray(__ptr, 2);
}
}
```
=> Fix IntPtr array marshalling bug and move hard to read code to CppSharp.Runtime

src/Generator/Generators/CSharp/CSharpSources.cs
```.cs
public static byte UChr
{
get
{	
// Performance killer: ResolveSymbol calls GetCurrentDirectory / File.Exists / LoadLibrary / GetProcAddress
var __ptr = (byte*)CppSharp.SymbolResolver.ResolveSymbol(image, "?UChr@StaticVariables@@2EB");
return *__ptr;
}
}
public static byte UChr
{
get
{
// Now its as simple as accessing a pointer from a static variable that doesn't change
var __ptr = (byte*)global::CSharp.__Symbols.CSharp_Native_dll._UChr_StaticVariables__2EB; 
return *__ptr;  
}
}
```
=> Load symbols at startup to avoid very expensive ResolveSymbol calls everywhere

tests/CSharp/CSharp.Tests.cs, tests/CSharp/CSharp.cpp, tests/CSharp/CSharp.h, tests/Tests.h
> System.TypeLoadException : Invalid unmanaged calling convention: must be one of stdcall, cdecl, or thiscall.
=> Remove unsupported calling convention usage

src/Generator/Types/Std/Stdlib.cs, tests/Common/Common.Tests.cs
Fixes #1441 but not completely till #1449 is resolved.
=> Prevent string destructor from being called twice when its passed by value

.github/workflows/main.yml
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
> In order to solve this, we’ve added a new pull_request_target event, which behaves in an almost identical way to the pull_request event with the same set of filters and payload. However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request.
=> Use pull_request_target to fix permission issue when running nunit-reporter step

build/Helpers.lua, build/Tests.lua, src/Generator.Tests/GeneratorTest.cs, tests/NamespacesBase/premake4.lua
This is necessary in order to easily find the compiled symbols as dependencies and target of platform invocation.
=> Generate code from tests where libraries appear

tests/CLI/CLI.h, tests/CSharp/CSharp.h, tests/CSharp/CSharpTemplates.h, tests/Common/Common.h, tests/Encodings/Encodings.h, tests/StandardLib/StandardLib.h, tests/Tests.h, tests/VTables/VTables.h
The warning is essentially a bug in msvc because it's harmless and requires exporting all accessible template specializations. See also http://www.unknownroad.com/rtfm/VisualStudio/warningC4251.html.
=> Disable the msvc warning about unexported template specializations

src/Generator.Tests/GeneratorTest.cs, tests/CSharp/CSharpTemplates.cpp, tests/CSharp/CSharpTemplates.h
The only function to use the specialization in question is actually ignored because the types of two of its parameters aren't supported. This was hidden by an otherwise redundant definition of a C++ symbol which is now removed.
=> Ensure a tested specialization is really generated

Directory.Build.props, src/Parser/CppSharp.Parser.csproj
Too few people would use a win 32 host nowadays.
=> Remove win x86 from the NuGet for smaller size

src/Generator/Generators/CLI/CLIMarshal.cs, tests/CLI/CLI.h
Mini-sample
C++->CLI
``` cpp
typedef signed char schar;
int fun1(signed char x) { return x; } // passed
int fun2(schar x) { return x; } // Cannot marshal argument of function 'fun2'
```
=> Fixed alias of signed char cannot be marshaled

src/CppParser/Parser.cpp
The Visual Studio C++ compiler does not allow to access Headers[i+1]
when i+1 points past the last element.
Doing so raises an exception when in
debug mode
=> Fix for "vector subscript out of range" exception

src/CLI/Generator.cs
In src/CLI/Generator.cs, the setup function doesn't add options.LibraryDirs to the module, and ClangParser cannot find input libraries.
https://github.com/mono/CppSharp/blob/b3d32d8c7109d8d64ef82e51b99c6068045ab93e/src/CLI/Generator.cs#L124-L127
I have tried passing full path to -l option but didn't work. According to this part, it looks like if the LibraryDirs is empty, then it will not process any library passed into it.
https://github.com/mono/CppSharp/blob/b3d32d8c7109d8d64ef82e51b99c6068045ab93e/src/CppParser/Parser.cpp#L4613-L4652
=> Add options.LibraryDirs to module in Generator.cs

src/Generator/Generators/C/CppHeaders.cs, src/Generator/Generators/C/CppSources.cs, src/Generator/Generators/CLI/CLIHeaders.cs, src/Generator/Generators/CLI/CLISources.cs, src/Generator/Generators/CSharp/CSharpSources.cs, src/Generator/Generators/CodeGenerator.cs, src/Generator/Options.cs, tests/CSharp/CSharp.CSharp.csproj, tests/CSharp/CSharp.Gen.cs, tests/CSharp/CSharp.Tests.cs, tests/CSharp/CSharp.h, tests/CSharp/CSharpPartialMethods.cs
If you turn on the option `Options.GenerateFinalizers` when generating a C# binding, C# finalizer methods are (indeed) generated. The generator also (typically) generates code in C# constructors so that the mapping between native memory addresses and managed instances can be recovered by using the static concurrent dictionary, `NativeToManagedMap`. This mapping is removed from the dictionary if the class' `Dispose` method is called. However, if Dispose is not called, the static dictionary holds a dangling reference to the mapped instance, preventing it from ever being finalized and collected by the garbage collector. This typically results in a memory leak of both managed and unmanaged memory.
- If  `Options.GenerateFinalizers` is set to `true`, this PR uses the class …
=> Use WeakReference<T> in NativeToManagedMap to allow finalizers to run.

src/Generator/Passes/ExpressionHelper.cs, tests/CSharp/CSharp.Tests.cs, tests/CSharp/CSharp.h
Consider the class:
``` c++
#define STRING_INITIALIZER "The quick brown fox"
struct /*DLL_API*/ MoreVariablesWithInitializer
{
static constexpr const char* IndependentStringVariable = STRING_INITIALIZER;
static constexpr const char* DependentStringVariable = IndependentStringVariable;
};
```
With `DLL_API` commented out on the class as above, when the variable `DependentStringVariable` is visited in `HandleVariableInitializerPass.VisitVariableDecl` we eventually call down to `ExpressionHelper.CheckForString` and at ExpressionHelper line 428 we execute: 
``` c#
if (typeInSignature is CILType managed && managed.Type == typeof(string))
{
result = result[result.IndexOf("\"")..];
return true;
}
```
At that point, `result` holds the (unquoted) string `IndependentStringVariable`. Consequently, …
=> Avoid ArgumentOutOfRangeException in ExpressionHelper.CheckForString

src/Generator/Generators/CSharp/CSharpSources.cs
This is an ugly change to make it work, but it's not perfect.
Changes:
* Do not generate `__GetInstance` method, doesn't work without a NativeToManaged map
* Do not generate much of the vtable interop call code, because that one doesn't work without `__GetInstance`
* Throw an exception if people try to inherit from a class with disabled NativeToManaged class (see explanation in code)
Two things I don't like, but don't really have time right now to properly fix:
* We should seal the class instead of throwing an exception in the constructor, but it seems like this would require lots of changes
* We should just get rid of all calls to SetupVTable() instead of gutting the method, but again, requires lots of work
Hint: View pull request with whitespace ignored, it's mostly just indention …
=> Fix disabling NativeToManaged map for classes with vtable
